### PR TITLE
feat: support live preview mode

### LINKED ISSUE #1: Display buttons in preview mode
Please like or plus one this issue if you’re interested in having the buttons display in preview mode.

### PR DESCRIPTION
**Pull request by scooper4711**

### CODE REVIEW

**Comment by scooper4711** [comment]
@tasyne - you said you were able to test plugins? Could you test this? I don’t like releasing code that hasn’t had another set of eyes on it. :)

just take it for a quick spin.

**Comment by tasyne** [comment]
@scooper4711 - correct! Good news, all seems to work on my box. I've noticed the following, which may just be little bits of cleanup or new features. The main functionality for this feature all worked for me. I did not see any page-switching bugs, for example.

1)
Upon loading Obsidian:
Uncaught (in promise) ReferenceError: syrinscape is not defined

plugin:syrinscape-player-control:1000 

console.log("Syrinscape - Activating Syrinscape player.");
await syrinscape.config.init();

(also receive these same console errors when clicking a "play" button pre-activation)
A long-term recommendation could be: graying out all play/stop buttons and converting the hover text to "please initialize the audio context by clicking the button in the 'Syrinscape Online Player' plugin tab"


2) 
Latent debug messages: "SyrinscapePlayerWidget toDOM" in "editing" mode, when going from the `syrinscape:...` markdown to the unicode icon rendering.


3) 
- in "source" mode, ("Current view: Editing", which displays the book icon): Only the "stop" button for the sound/mood ID that is currently playing will be able to actually stop the sound. No other stop buttons work except the one on the plugin tab, or a different stop button for the same sound/mood ID. In contrast, other "play" buttons will halt any other sounds that are playing, and then play their own. 
- in "reading" mode ("Current view: Reading", which displays the pencil icon), this functionality is identical to "source" mode, as described earlier.
Edit: confirmed that the main branch has identical functionality as item number 3^

**Comment by scooper4711** [comment]
Thank you so much @tasyne! 

1a. Getting syrinscape properly initialized in all cases is proving to be difficult. I think I'll move this one to a separate bug. If you can provide reliable steps to recreate, that would be helpful. In particular, since I have the player auto-activate, I'm looking for how you were able to get it to not be active. There's two steps - activation (which establishes a web socket) and login (which sends the login token). I automatically do activation upon successful Obsidian initialization. But sometimes it doesn't work. I haven't figured out how to reliably recreate that.

1b. Greying out buttons until fully activated and logged in - very good idea. I'll log that as a feature request.

2. Thanks for spotting that. Squashed.

3. This is the syrinscape behavior for moods. Only one mood is ever playing at a time. So if you start a new mood, the old one turns off. Sound Effects and Music are different - you can start a mood, then add or remove sound effect and music loops by pressing play/stop. The Player widget has a "stop all" button, which just stops all elements that are currently playing.  Would you prefer a different approach? What, in that case?

**Comment by tasyne** [comment]
>     3. This is the syrinscape behavior for moods. Only one mood is ever playing at a time. So if you start a new mood, the old one turns off. Sound Effects and Music are different - you can start a mood, then add or remove sound effect and music loops by pressing play/stop. The Player widget has a "stop all" button, which just stops all elements that are currently playing.  Would you prefer a different approach? What, in that case?

The way I use deep-urls + Obsidian in my notebooks now, is to have a single long (ish) document for each game session. This will include headings for various places I expect my players to go. Anyways, I find myself in the situation where I need to play a sound for the area, and then play another sound from a button/url further down the document. In the case of starting a different mood from syrinscape, this is fine. I will hit "play" and the old mood will disappear. Most of my use for Syrinscape is for moods, not effects. However, I have a number of audio background "moods" that are simply .mp3 files from quite a large library. I've been able to use deep-urls with VLC to achieve a similar effect, but I need to stop syrinscape playing before I click a VLC URL. If clicking a ▶️ button causes any currently playing syrinscape mood to cease (supplanted by a new one) then why wouldn't any ⏹️ button also cause any mood that is playing to halt? The behavior of one is global, the behavior of the other is tied to the mood that is playing (and it is difficult to determine which mood is playing). These ▶️⏹️ buttons are excellent for managing the player, and are probably all I need in order to be able to hide the syrinscape player plugin window entirely, but in the case of working with non syrinscape sounds, I need a way to reliably halt syrinscape. In my use-case, that halt behavior would be anywhere I see a ⏹️, instead of having to hunt for the ▶️⏹️ that started the mood, or opening the syrinscape player panel.

^My use hinges on basically not using the music loops. Really just using moods (and the occasional monster sound effect). Another way to address this use-case could be to show which loops and moods are currently playing. Perhaps in the markdown (🎵), perhaps in the syrinscape player plugin window. 

Just thought I'd share how I use it. I can see how non-mood music loops may throw a wrench into handling a player that does more than how I view syrinscape.

**Comment by scooper4711** [comment]
I understand your use case. This makes sense.
So how about:
mood: stop button stops all
music or sfx: stop button stops only that one music or sfx
one shot: no stop button.

Should I indicate "stop all" differently from "stop this one thing"? (other than tool tip of course).
Hmm. Maybe next to a music or sfx, it's a pause button instead of a stop button?

**Pull request merged**
